CREATE TABLE belly_splitter (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    item_id INTEGER REFERENCES belly_item(id) ON DELETE CASCADE,
    nickname TEXT NOT NULL,
    avatar TEXT NOT NULL,
    share_qty INTEGER NOT NULL,
    created_at TIMESTAMP DEFAULT now() NOT NULL,
    deleted TIMESTAMP
);